camera:
  SN: "26883050"
  SN1: "26883050"
  SN2: "4002885218"
  dataformat: "XI_MONO8"
  data_min: 0  # Minimum image output value
  data_max: 255  # Maximum image output value for dataformat 1023 for actual camera
  exposure: 40000  # us 40000, 250000
  auto_gain: 0  # Flag for whether to use automatic exposure / gain mode, 0-auto_gain off, 1-auto_gain on
  exp_priority: 0.8  # Exposure n, gain (1 - n)
  ae_max_limit: 100000  # Maximum time (us) used for exposure in AEAG procedure
  burst_mode: 0  # Flag for whether to use burst mode, 0-burst_mode off, 1-burst_mode on 
  burst_frames: 10  # Number of frames to acquire in burst mode
  acq_timing_mode: "XI_ACQ_TIMING_MODE_FRAME_RATE"
  trigger_source: "XI_TRG_SOFTWARE"
  timeout: 1000  # us Time to wait before timeout error is raised
  frame_rate: 20.0  # Hz 20, 3
  sensor_width: 2048  # pixels Ximea - 2048, IDS - 1024
  sensor_height: 2048  # pixels Ximea - 2048, IDS - 1024
  sensor_diam: 11.26  # mm Ximea - 11.26, IDS - 4.762
  bin_factor: 2  # Ximea - 2, IDS - 1
  pixel_size: 5.5  # um Ximea - 5.5, IDS - 4.65
  frame_num: 1  # Number of frames to acquire in image acquisition mode 1
  sleep_time: 0.1  # Interval time between frames during live acquisition
    
DM:
  SN: "HSDM69-15-014" 
  DM_num: 0  # Flag for choosing the working DM, 0-Alpao, 1-Boston
  exercise: 1  # Flag for whether to exercise DM upon initialisation
  exercise_num: 50  # Number of shapes used during DM exercise
  vol_min: -0.1  # V
  vol_max: 0.1  # V
  vol_bias: 0
  vol_step: 1
  settling_time: 0.001

DM0: 
  actuator_num: 69  # Alpao
  pitch: 1500  # um
  aperture: 10.5  # mm
  coupling_fac: 0.3  # Inter-actuator coupling factor

DM1:
  actuator_num: 140  # Boston
  pitch: 400  # um  
  aperture: 4.4  # mm  
  coupling_fac: 0.13  # Inter-actuator coupling factor

relay:
  mirror_odd: 0  # Flag for whether there is an odd number of mirrors in between DM and lenslet
  relay_odd: 0  # Flag for whether there is an odd number of relays in between DM and lenslet

lenslet:
  lenslet_pitch: 150  # um 500 300 150
  lenslet_focal_length: 5200  # um 32800 15300 10000 8700 5200

search_block:
  div_elem: 5  # Number of elements in each dimension of a search block
  filter_thres: 10  # Cutoff value for low pass filter within each search block after Fourier transform
  sharp_thres: 0.002  # Minimum sharpness threshold within search block below which S-H spot will be considered as obscured
  outline_int: 255  # uint8
  pupil_diam_0: 2.2  # mm Alpao 7.216 (500) / 4.5 (300) / 2.2 (1.92, 2, 2.35, 2.5) (150)
  pupil_diam_1: 10.1  # mm Boston 10.1 (500) / 6.3 (300) / 3.1 (150)

image:
  noise: 0.1  # The uniform noise level for synthetic samples
  threshold: 0.02  # Percentage of maximum pixel used for thresholding an image, 0.03
  dynamic_num: 1  # Number of cycles to use for centroiding with a dynamic range
  normalise: 1  # 0 - normalise off, 1 - normalise on
  norm_min: 0  # Below which will clip to 0, uint8
  norm_max: 255  # Above which will clip to 1, uint8
  rescale: 1  # 0 - rescale off, 1 - rescale on

sys_calib:
  sys_calib_mode: 1  # Mode flag for system aberration calibration method, 0 - calculate present centroids, 1 - load precalibrated voltages before calculating present centroids

AO:
  zern_gen: 1  # Flag for generating zernike modes on DM in AO_zernikes.py and AO_slopes.py, 0 - off, 1 - iterative generation
  loop_max_gen: 15  # Maximum number of loops for closed-loop control during generation of zernike modes
  recon_coeff_num: 69  # Number of zernike modes to use during wavefront reconstruction
  control_coeff_num: 20  # Number of zernike modes to control during AO correction  # 3rd - 14, 4th - 20, 5th - 27, 6th - 35, 7th - 44, 8th - 54, 9th - 65, 10th - 77
  loop_gain: 0.2  # Fixed loop gain for closed-loop control during AO correction
  suppress_gain: 10000  # Gain factor used to suppress certain zernike modes
  lambda: 0.83  # um 0.63 / 0.83
  tolerance_fact_strehl: 1  # Strehl ratio tolerance factor according to Marechel criteria, 0.81

data_collect:
  data_collect_mode: 0  # Mode flag for Data Collection button, detailed function descriptions in app.py
  mult_mode_gen: 1 # Flag for generating single/multiple zernike modes in mode 2, 0 - single, 1 - multiple
  loop_max_gen: 15  # Maximum number of loops during closed-loop generation of zernike modes in mode 0/1/2/3
  incre_num: 10  # Number of zernike mode amplitudes to generate in mode 0/1
  incre_amp: 0.02  # Increment amplitude between zernike modes in mode 0/1
  run_num: 10  # Number of times to run mode 0/1/2/3

RF_calib:
  calib_step_num: 11  # Number of steps used in one direction during calibration of remote focusing
  calib_step_incre: 10  # um Axial increment between each step during calibration of remote focusing 
  calib_direct: 0  # Direction of calibration, 0-negative, 1-positive

RF:
  step_incre: 0.1  # um Axial increment between each step during actual remote focusing
  index_offset: 900  # Index offset in voltage lookup table