fpga:
  resource: "RIO0"
  bitfile: "bitfiles/doptical_7855R.lvbitx"
  dma_max_length: 1023 
  waveform_max_length: 1023
  AO_min: -10  # V
  AO_max: 10  
  IO_datatype: "FXP"

lenslet:
  lenslet_pitch: 500  # um
  lenslet_focal_length: 45  # mm

camera:
  SN: "26883050"
  dataformat: "XI_MONO16"
  exposure: 4000  # us
  auto_gain: 0  # Flag for whether to use automatic exposure / gain mode, 0-auto_gain off, 1-auto_gain on
  exp_priority: 0.8  # exposure n, gain (1 - n)
  ae_max_limit: 500000  # maximum time (us) used for exposure in AEAG procedure
  burst_mode: 0  # Flag for whether to use burst mode, 0-burst_mode off, 1-burst_mode on 
  burst_frames: 10
  acq_timing_mode: "XI_ACQ_TIMING_MODE_FREE_RUN"
  sensor_width: 2048  # pixels
  sensor_height: 2048  # pixels
  pixel_size: 5.5  # um
  frame_ave_num: 5
  
DM:
  actuator_num: 69
  vol_min: -1  # V
  vol_max: 1
  vol_bias: 0
  vol_step: 1

search_block:
  outline_int: 255  # uint8
  cent_thres: 5  # uint8
  pupil_diam: 7.5  # mm

AO:
  recon_coeff_num: 70
  control_coeff_num: 69
  sys_mode_num: 69
  loop_gain: 0.1
  momentum: 
