fpga:
  resource: "RIO0"
  bitfile: "bitfiles/doptical_7855R.lvbitx"
  dma_max_length: 1023 
  waveform_max_length: 1023
  AO_min: -10  # V
  AO_max: 10  
  IO_datatype: "FXP"

lenslet:
  lenslet_pitch: 500  # um
  lenslet_foclength: 45  # mm

camera:
  SN: "26883050"
  dataformat: "XI_MONO8"
  exposure: 2000
  sensor_width: 2048  # pixels
  sensor_height: 2048  # pixels
  pixel_size: 5.5  # um
  frame_ave_num: 5
  
DM:
  actuator_num: 69
  vol_min: -1  # V
  vol_max: 1
  vol_bias: 0
  vol_step: 1

search_block:
  outline_int: 255  # uint8
  spots_across_diam: 13
  cent_thres: 5  # uint8

AO:
  recon_coeff_num: 70
  control_coeff_num: 69
  sys_mode_num: 69
  loop_gain: 0.1
  momentum: 
