fpga:
  resource: "RIO0"
  bitfile: "bitfiles/doptical_7855R.lvbitx"
  dma_max_length: 1023 
  waveform_max_length: 1023
  AO_min: -10  # V
  AO_max: 10  
  IO_datatype: "FXP"

camera:
  SN: "26883050"
  # SN: "4002885218"
  dataformat: "XI_MONO8"
  data_min: 0  # Minimum image output value
  data_max: 255  # Maximum image output value for dataformat 1023 for actual camera
  exposure: 150  # us
  auto_gain: 0  # Flag for whether to use automatic exposure / gain mode, 0-auto_gain off, 1-auto_gain on
  exp_priority: 0.8  # exposure n, gain (1 - n)
  ae_max_limit: 100000  # maximum time (us) used for exposure in AEAG procedure
  burst_mode: 0  # Flag for whether to use burst mode, 0-burst_mode off, 1-burst_mode on 
  burst_frames: 10
  acq_timing_mode: "XI_ACQ_TIMING_MODE_FREE_RUN"
  frame_rate: 5  # Hz
  sensor_width: 2048  # pixels Ximea - 2048; IDS - 1024
  sensor_height: 2048  # pixels Ximea - 2048; IDS - 1024
  sensor_diam: 11.26  # mm Ximea - 11.26; IDS - 4.762
  bin_factor: 2  # Ximea - 2; IDS - 1
  pixel_size: 5.5  # um Ximea - 5.5; IDS - 4.65
  frame_num: 5  # Number of frames to acquire in burst acquisition mode 
  sleep_time: 0.1  # Interval time between frames during live acquisition
    
DM:
  SN: "HSDM69-15-014" 
  DM_num: 0  # Flag for choosing the working DM, 0-Alpao, 1-Boston
  vol_min: -0.05  # V  -0.06
  vol_max: 0.05  # V  0.06
  vol_bias: 0
  vol_step: 1
  settling_time: 0.01

DM0: 
  actuator_num: 69  # Alpao
  pitch: 1500  # um
  aperture: 10.5  # mm
  coupling_fac: 0.3  # Inter-actuator coupling factor

DM1:
  actuator_num: 140  # Boston
  pitch: 400  # um  
  aperture: 4.4  # mm  
  coupling_fac: 0.13  # Inter-actuator coupling factor, 0.26 works better...

scanner:
  SN: "S31155"
  portnumber: "3"

relay:
  mirror_odd: 0  # Flag for whether there is an odd number of mirrors in between DM and lenslet
  relay_odd: 0  # Flag for whether there is an odd number of relays in between DM and lenslet

lenslet:
  lenslet_pitch: 150  # um  500 300 150
  lenslet_focal_length: 5200  # um  32800 15300 10000 8700 5200

search_block:
  div_elem: 5  # Number of elements in each dimension of a search block
  filter_thres: 10  # Cutoff value for low pass filter within each search block after Fourier transform
  sharp_thres: 0.002  # Minimum sharpness threshold within search block below which S-H spot will be considered as obscured
  outline_int: 255  # uint8
  pupil_diam_0: 1.92  # mm  # Alpao 7.216 (500) / 4.5 (300) / 2.2 (1.92) (150)
  pupil_diam_1: 10.1  # mm  # Boston 10.1 (500) / 6.3 (300) / 3.1 (150)

image:
  noise: 0.1  # The uniform noise level for synthetic samples
  threshold: 0  # Percentage of maximum pixel used for thresholding an image
  dynamic_num: 1  # Number of cycles to use for centroiding with a dynamic range
  normalise: 1  # 0-normalise off, 1-normalise on
  norm_min: 0  # Below which will clip to 0, uint8
  norm_max: 255  # Above which will clip to 1, uint8
  rescale: 1  # 0-rescale off, 1-rescale on

AO:
  zern_gen: 0  # Flag for whether to generate Zernike modes on DM before correction in AO_zernikes.py and AO_slopes.py
  scan_flag: 0  # Flag for whether to perform scanning during AO correction
  scan_num_x: 20  # Number of scan points along x direction
  recon_coeff_num: 80  # 80
  control_coeff_num: 69  # Alpao 46  # Boston 55  # 3rd - 14, 4th - 20, 5th - 27, 6th - 35, 7th - 44, 8th - 54, 9th - 65, 10th - 77
  loop_gain: 0.2  # Fixed loop gain for closed-loop control, 0.6
  loop_max: 20  # Maximum number of loops for closed-loop control
  suppress_gain: 1000  # Gain factor used to suppress certain zernike modes
  lambda: 0.83  # um 0.63 / 0.83
  tolerance_fact_zern: 0  # RMS error tolerance factor via zernikes, 0.045 = lambda / 14
  tolerance_fact_strehl: 1  # Strehl ratio tolerance factor according to Marechel criteria, 0.81

zern_test:
  zern_test_mode: 2  # Flag for Zernike Test button operation mode, 0 - AO via Zernikes, 1 - AO via slopes, 2 - line scan + retrieve Zernike coefficients
  zern_amp: 0.1  # Amplitude of all zernike modes for comparison
  loop_num: 20  # Number of line scans to loop over in mode 2
  scan_num_x: 50  # Number of scan points along x direction in mode 2
  scan_num_y: 50  # Number of scan points along y direction in mode 2
  x_amp: 0.1  # Normalised voltage range for x scan, max/min +/-1V (600 um)
  y_amp: 0.1  # Normalised voltage range for y scan, max/min +/-1V (600 um)

RF_calib:
  step_num: 5  # Number of steps used in one direction during calibration of remote focusing
  step_incre: 1  # Axial increment between each step / um

reflect_prof:
  samp_num: 33  # Flag for choosing the working sample
  samp_width: 128  # pixels  # Note that this has to be a factor of the sensor width
  bead_num: 50  # Number of beads in simulated bead sample image 2000
  bead_sigma: 1  # Sigma value for generating Gaussian profile beads 
  background: 20  # Intensity value for background of bead sample image
  obj_grid_size: 128  # Size of object space grid (128 for simulation sample)

ML:
  OPL: 1.15  # um
  zern_num: 20  # Number of zernike modes applied
  samp_num: 1  # Number of samples used
  aberr_num: 18  # Number of aberration combinations
  zern_amp_3: 0.075  # Amplitude of applied Zernike modes 0.075
  zern_amp_5: 0.2
  zern_amp_6: 0.2
  zern_amp_7: 0.35
  zern_amp_8: 0.8
  zern_amp_9: 0.7
  zern_amp_10: 0.3
  zern_amp_11: 0.075
  zern_amp_12: 0.5
  zern_amp_13: 0.1
  zern_amp_14: 0.5
  zern_amp_15: 0.02
  zern_amp_16: 0.04
  zern_amp_17: 0.15
  zern_amp_18: 0.5
  zern_amp_19: 0.5
  zern_amp_20: 0.3
  tilt_amp: 2.4  # Maximum amount of tilt for scanning across synthetic image 1.5
  tip_amp: 0  # Maximum amount of tip for scanning across synthetic image 1.5
  scan_num_x: 50  # Number of scan points along x direction 20
  scan_num_y: 1  # Number of scan points along y direction 20
  obj_grid_size: 128  # Size of object space grid

dummy: 0  # Flag for whether to run in dummy mode, 0-real mode, 1-dummy mode
real_phase: 0  # Flag for whether to use real phase data, 0-zernike phase, 1-real phase
real_zernike: 0  # Flag for whether to generate real zernike modes using DM control matrix, 0-ideal zernike, 1-real zernike
reflect_on: 0  # Flag for whether to incorporate sample reflectance process
noise_on: 0  # Flag for whether to add noise to synthetic images