fpga:
  resource: "RIO0"
  bitfile: "bitfiles/doptical_7855R.lvbitx"
  dma_max_length: 1023 
  waveform_max_length: 1023
  AO_min: -10  # V
  AO_max: 10  
  IO_datatype: "FXP"

camera:
  SN: "26883050"
  dataformat: "XI_MONO16"
  data_min: 0  # Minimum image output value
  data_max: 1023  # Maximum image output value for dataformat
  exposure: 4000  # us
  auto_gain: 0  # Flag for whether to use automatic exposure / gain mode, 0-auto_gain off, 1-auto_gain on
  exp_priority: 0.8  # exposure n, gain (1 - n)
  ae_max_limit: 500000  # maximum time (us) used for exposure in AEAG procedure
  burst_mode: 0  # Flag for whether to use burst mode, 0-burst_mode off, 1-burst_mode on 
  burst_frames: 10
  acq_timing_mode: "XI_ACQ_TIMING_MODE_FREE_RUN"
  frame_rate: 5  # Hz
  sensor_width: 2048  # pixels
  sensor_height: 2048  # pixels
  bin_factor: 2
  pixel_size: 5.5  # um
  frame_ave_num: 5
    
DM:
  SN: "HSDM69-15-014"
  actuator_num: 69
  pitch: 1500  # um
  aperture: 10.5  # mm
  coupling_fac: 0.13  # Inter-actuator coupling factor
  vol_min: -1  # V
  vol_max: 1
  vol_bias: 0
  vol_step: 1
  settling_time: 0.05

relay:
  mirror_odd: 0  # Flag for whether there is an odd number of mirrors in between DM and lenslet
  relay_odd: 0  # Flag for whether there is an odd number of relays in between DM and lenslet

lenslet:
  lenslet_pitch: 500  # um
  lenslet_focal_length: 45000  # um

search_block:
  div_elem: 5  # Number of elements in each dimension of a search block
  outline_int: 255  # uint8
  pupil_diam: 7.216  # mm 7.216 8.4

image:
  noise: 0
  threshold: 0  # Percentage of maximum pixel used for thresholding an image
  dynamic_num: 2  # Number of cycles to use for centroiding with a dynamic range
  normalise: 1  # 0-normalise off, 1-normalise on
  norm_min: 0  # Below which will clip to 0, uint8
  norm_max: 255  # Above which will clip to 1, uint8
  rescale: 1  # 0-rescale off, 1-rescale on

AO:
  recon_coeff_num: 60
  control_coeff_num: 37
  loop_gain: 0.1  # Fixed loop gain for closed-loop control
  loop_max: 50  # Maximum number of loops for closed-loop control
  lambda: 0.83  # um
  tolerance_fact_zern: 0.06  # RMS error tolerance factor via zernikes, = lambda / 14 um
  tolerance_fact_slopes: 0.001
  tolerance_fact_strehl: 0.81
  momentum: 

dummy: 1  # Flag for whether to run in dummy mode, 0-real mode, 1-dummy mode
real_phase: 1  # Flag for whether to use real phase data